apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logdrains.kcd.io
spec:
  group: kcd.io
  scope: Cluster  # a CRD can also be Namespaced
  names:
    plural: logdrains
    singular: logdrain
    kind: LogDrain
    shortNames:
    - ld
  versions:
  - name: v1alpha1  # you can serve multiple versions e.g v1beta2 or v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              target:
                type: string
    additionalPrinterColumns:
    - name: Target
      type: string
      description: Looks for pod with target label
      jsonPath: .spec.target        
