apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logdrains.dev.io
spec:
  group: dev.io # /apis/<group>/<version>
  scope: Cluster  # can also be Namespaced
  names:
    plural: logdrains
    singular: logdrain
    kind: LogDrain
    shortNames:
    - ld
  versions:
  - name: v1alpha1  # you can serve multiple versions e.g v1beta2 or v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: LogDrain is a resource that allows the configuration of demo-operator
        properties:
          spec:
            type: object
            description: Specification for managing log aggregation to the demo-operator drain
            properties:
              target:
                description: Set the target to the desired label value, for the operator to pick
                type: string
    additionalPrinterColumns:
    - name: Target
      type: string
      description: Looks for pod with target label
      jsonPath: .spec.target        
