apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qos-controller-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["dev.io"]
  resources: ["qoses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qos-controller-binding
subjects:
- kind: ServiceAccount
  name: go-controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: qos-controller-role
  apiGroup: rbac.authorization.k8s.io
